#!/bin/bash
set -e

echo "==============================="
echo "   WordPress Stack Installer   "
echo "==============================="

FORCE=false
LANG=""
for arg in "$@"; do
    [ "$arg" = "--force" ] && FORCE=true
    [[ "$arg" == --lang=* ]] && LANG="${arg#--lang=}"
done

# Check if already installed + reinstall mechanism
if [ -f ".env" ] || [ -d "db_data" ] || [ -d "wordpress" ]; then
    if [ "$FORCE" = true ]; then
        echo "Force reinstall — removing existing installation..."
        docker compose down -v
        docker run --rm -v "$(pwd)/db_data:/db_data" alpine sh -c "rm -rf /db_data/* /db_data/.*" 2>/dev/null || true
        docker run --rm -v "$(pwd)/wordpress:/wordpress" alpine sh -c "rm -rf /wordpress/* /wordpress/.*" 2>/dev/null || true
        rmdir db_data wordpress 2>/dev/null || true
        rm -f .env
    else
        echo "Error: .env file already exists. Looks like the stack is already installed."
        echo "To reinstall, run: ./install.sh --force"
        echo "Warning: this will delete all database data."
        exit 1
    fi
fi



# Setup Questions
read -p "Enter domain (e.g. site.local): " DOMAIN
if [ -z "$DOMAIN" ]; then
    echo "Error: domain cannot be empty"
    exit 1
fi

read -p "WP Site Title: " TITLE

read -p "WP Admin User [admin]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-admin}

read -s -p "WP Admin Pass [autogenerated]: " ADMIN_PASS
ADMIN_PASS=${ADMIN_PASS:-$(openssl rand -base64 16 | tr -d '/+=1IlO0S5')}
echo ""

read -p "WP Admin Email [admin@$DOMAIN]: " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@$DOMAIN}

echo ""

# Config & Passwords
DB_ROOT_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')
DB_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')

cp .env.dist .env
sed -i 's/\r//' .env
sed -i "s/^DOMAIN_NAME=.*/DOMAIN_NAME=$DOMAIN/" .env
sed -i "s/^DB_ROOT_PASSWORD=.*/DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD/" .env
sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/" .env
export $(grep -v '^#' .env | xargs)

# SSL & Config
mkdir -p wordpress db_data
sed "s/{{DOMAIN}}/$DOMAIN/g" nginx/ssl/domain.ext.dist > "nginx/ssl/$DOMAIN.ext"
sed "s/{{DOMAIN}}/$DOMAIN/g" nginx/conf.d/default.conf.dist > "nginx/conf.d/default.conf"

if [ ! -f "nginx/ssl/rootCA.pem" ]; then
    openssl genrsa -out nginx/ssl/rootCA.key 2048
    openssl req -x509 -new -nodes -key nginx/ssl/rootCA.key -sha256 -days 3650 -out nginx/ssl/rootCA.pem -subj "/C=PL/ST=Local/O=Dev/CN=LocalDevRootCA"
fi
openssl genrsa -out "nginx/ssl/$DOMAIN.key" 2048
openssl req -new -key "nginx/ssl/$DOMAIN.key" -out "nginx/ssl/$DOMAIN.csr" -subj "/C=PL/ST=Local/O=Dev/CN=$DOMAIN"
openssl x509 -req -in "nginx/ssl/$DOMAIN.csr" -CA nginx/ssl/rootCA.pem -CAkey nginx/ssl/rootCA.key -CAcreateserial -out "nginx/ssl/$DOMAIN.crt" -days 825 -sha256 -extfile "nginx/ssl/$DOMAIN.ext"

# Start Infrastructure
docker compose up -d mysql wordpress nginx

# Wait for MySQL
RETRIES=30
until docker compose exec mysql mysql -u"$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1;" "$DB_NAME" &>/dev/null; do
    RETRIES=$((RETRIES - 1))
    if [ $RETRIES -eq 0 ]; then
        echo "Error: MySQL did not become ready in time"
        exit 1
    fi
    echo "Waiting..."
    sleep 2
done || true

# WP-CLI - Setup
# memory_limit=512M - prevents memory errors
echo "Creating config..."
docker compose run --rm \
    -e WP_CLI_PHP_ARGS="-d memory_limit=512M" \
    wpcli wp config create \
    --dbname="$DB_NAME" \
    --dbuser="$DB_USER" \
    --dbpass="$DB_PASSWORD" \
    --dbhost="mysql" \
    --force

echo "Installing..."
docker compose run --rm wpcli wp core install \
    --url="https://$DOMAIN" \
    --title="$TITLE" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASS" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-email

if [ -n "$LANG" ]; then
    echo "Installing language pack: $LANG..."
    docker compose run --rm wpcli wp language core install "$LANG" --activate
fi

# FIX PERMISSIONS
echo "Fixing permissions..."
docker compose exec -u root wordpress chmod -R u=rwX,go=rX /var/www/html
docker compose exec -u root wordpress chmod 640 /var/www/html/wp-config.php

echo "================================================="
echo " DONE!"
echo ""
echo " Update your hosts file"
echo " and import ssl certificate to your browser"
echo ""
echo " Website: https://$DOMAIN"
echo " Admin panel: https://$DOMAIN/wp-admin"
echo ""
echo " admin email: $ADMIN_EMAIL"
echo " admin user: $ADMIN_USER"
echo " admin password: $ADMIN_PASS"
echo "================================================="